In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import random

Mounted at /content/drive


In [ ]:
xy = np.loadtxt('/content/drive/MyDrive/Colab_Notebooks/Baseball data/DATASET_TEST_V3.csv',delimiter=',',dtype = np.float32)

x_data = xy[:,0:-1]
y_data = xy[:,[-1]]
print(x_data.shape, y_data.shape)

learning_rate = 0.001
batch_size = 100
training_epochs = 500
nb_classes = 27


(8631, 42) (8631, 1)


In [ ]:
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(input_dim=42, units=20, kernel_initializer='glorot_normal', activation='relu'))
tf.model.add(tf.keras.layers.Dense(units=20, kernel_initializer='glorot_normal', activation='relu'))
tf.model.add(tf.keras.layers.Dense(units=nb_classes, kernel_initializer='glorot_normal', activation='softmax'))


tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate), metrics=['accuracy'])
tf.model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 20)                860       
_________________________________________________________________
dense_4 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_5 (Dense)              (None, 27)                567       
Total params: 1,847
Trainable params: 1,847
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = tf.model.fit(x_data, y_one_hot, epochs=training_epochs)


Epoch 1/1000
270/270 [==============================] - 3s 3ms/step - loss: 9.3786 - accuracy: 0.0902
Epoch 2/1000
270/270 [==============================] - 1s 3ms/step - loss: 2.2394 - accuracy: 0.2081
Epoch 3/1000
270/270 [==============================] - 1s 3ms/step - loss: 2.0178 - accuracy: 0.2370
Epoch 4/1000
270/270 [==============================] - 1s 3ms/step - loss: 1.8312 - accuracy: 0.2876
Epoch 5/1000
270/270 [==============================] - 1s 3ms/step - loss: 1.6612 - accuracy: 0.3498
Epoch 6/1000
270/270 [==============================] - 1s 3ms/step - loss: 1.5064 - accuracy: 0.3964
Epoch 7/1000
270/270 [==============================] - 1s 3ms/step - loss: 1.3909 - accuracy: 0.4679
Epoch 8/1000
270/270 [==============================] - 1s 3ms/step - loss: 1.2856 - accuracy: 0.5126
Epoch 9/1000
270/270 [==============================] - 1s 4ms/step - loss: 1.2356 - accuracy: 0.5511
Epoch 10/1000
270/270 [==============================] - 1s 4ms/step - loss: 1.179

In [ ]:
y_predicted = tf.model.predict(x_data)
for x in range(0, 100):
    random_index = random.randint(0, x_data.shape[0]-1)
    s=np.argsort(y_predicted[random_index])
    u=y_predicted[random_index][s]
    print("index: ", random_index,
          "\tactual y: ", np.argmax(y_one_hot[random_index]),
          "\tpredicted y: ", np.argmax(y_predicted[random_index])
          ,"\tpredicted best 3 score: ",np.flip(s)[:3],
           "\t" , np.flip(u)[:3] )



index:  132 	actual y:  7 	predicted y:  8 	predicted best 3 score:  [8 7 9] 	 [0.49480703 0.463746   0.03926045]
index:  3398 	actual y:  5 	predicted y:  6 	predicted best 3 score:  [6 5 7] 	 [0.49681795 0.3281128  0.09632185]
index:  5009 	actual y:  7 	predicted y:  7 	predicted best 3 score:  [7 8 9] 	 [0.5915104  0.27817672 0.1259048 ]
index:  4193 	actual y:  8 	predicted y:  9 	predicted best 3 score:  [ 9  8 10] 	 [0.66950876 0.25625992 0.06491472]
index:  1115 	actual y:  7 	predicted y:  7 	predicted best 3 score:  [7 8 9] 	 [0.71191657 0.2589651  0.02843866]
index:  4881 	actual y:  0 	predicted y:  0 	predicted best 3 score:  [0 1 2] 	 [0.7905507  0.19515097 0.0137166 ]
index:  1789 	actual y:  2 	predicted y:  2 	predicted best 3 score:  [2 3 4] 	 [0.9323876  0.04273716 0.02467422]
index:  5835 	actual y:  4 	predicted y:  5 	predicted best 3 score:  [5 4 6] 	 [0.53404075 0.42426676 0.03495587]
index:  6121 	actual y:  7 	predicted y:  8 	predicted best 3 score:  [8 7 9] 

In [ ]:
# evaluate test set
evaluation = tf.model.evaluate(x_data, y_one_hot)
print('loss: ', evaluation[0])
print('accuracy', evaluation[1])

270/270 [==============================] - 1s 3ms/step - loss: 0.7080 - accuracy: 0.7159
loss:  0.7079828977584839
accuracy 0.7159077525138855
